### ISSUE TITLE
InsufficientCredentials: The credentials used to authenticate this request are not authorized to execute this operation.

### ISSUE THREAD

**Issue by dheerajkhokhar** [Kinvey/kinvey-cli#202]
Hi, 

I tried to fetch files using this command:- "kinvey appenv export --file ./kinvey" then i got this "InsufficientCredentials: The credentials used to authenticate this request are not authorized to execute this operation." error message and my role on kinvey app is "Administrator".

Please help me to fix this issue. 

Thank you.

**Comment by DennyGD** [comment]
Hi, @dheerajkhokhar!

I would suggest running the CLI in verbose mode by appending the `--verbose` flag to the command you want to run. Example: 
`kinvey --verbose appenv export --file ./kinvey.json`

This will print additional debug messages and it will help us find out what permissions are missing.

Here you can find additional info about the app environment configuration files if needed: [https://github.com/Kinvey/kinvey-cli#environment-configuration-file](https://github.com/Kinvey/kinvey-cli#environment-configuration-file)

**Comment by dheerajkhokhar** [comment]
Hi, i run `kinvey --verbose appenv export --file ./kinvey.json` and getting same error.

```
dheeraj:sandbox dheeraj$ kinvey profile use dheeraj-sqm
Active profile: dheeraj-sqm
dheeraj:sandbox dheeraj$ bash sandbox.sh

======================== KINVEY STARTED ===========================

Active application: d6af0df5eee5448485c361b9xxxxxxxx

======================== KINVEY APP SET ===========================

Active environment: kid_cxxxxxxx

======================== KINVEY ENV SET ===========================

[debug] Checking for package updates
[debug] Using profile 'dheeraj-sqm'
[debug] Using environment: kid_cxxxxxxx
[debug] Request:  GET https://xxxxxxx-manage.kinvey.com/v4/environments/kid_cxxxxxxx
[debug] Response: GET https://xxxxxxx-manage.kinvey.com/v4/environments/kid_cxxxxxxx 200
Starting export for environment: SANDBOX(kid_cxxxxxxx)
[debug] Getting all services...
[debug] Using application: d6af0df5eee5448485c361b9xxxxxxxx
[debug] Request:  GET https://xxxxxxx-manage.kinvey.com/v4/apps/d6af0df5eee5448485c361b9xxxxxxxx
[debug] Response: GET https://xxxxxxx-manage.kinvey.com/v4/apps/d6af0df5eee5448485c361b9xxxxxxxx 200
[debug] Request:  GET https://xxxxxxx-manage.kinvey.com/v4/services
[debug] Response: GET https://xxxxxxx-manage.kinvey.com/v4/services 403
[error] InsufficientCredentials: The credentials used to authenticate this request are not authorized to execute this operation.
```

**Comment by DennyGD** [comment]
The output indicates that you don't have permissions to read services. When an app environment is exported, the CLI tries to get the organization's services and this is where the export fails. You should ask your organization's administrator to give you permissions.
  Even if the environment doesn't use any services, the export will still fail if the user has no service permissions. We will address this in the near future.
   Let me know if you need anything else.

**Comment by dimofeev** [comment]
Going to close the issue as the problem seems solved.
