### ISSUE TITLE
Getting Current Environment Version Returning Incorrect Value

### ISSUE THREAD

**Issue by kinson** [Kinvey/kinvey-cli#46]
Hello again!

I am not sure if this is correct place to put this issue since it doesn't seem to be an issue with the kinvey-cli package itself, but rather with the the service/server that kinvey-cli provides an interface to. However this defect has propagated to this tool in the result of the `kinvey status` command. 

For context I am on `2.0.0-beta.1`.

When I initially updated to the beta I ran the instructed one-time `kinvey recycle`. This completed successfully and I was able to initially get the service version number with `kinvey status`. However I noticed after a few updates that the result of `kinvey status` had not changed. The code block below is an except from a shell session that should illustrate the defect. As you can see below if I run `kinvey recycle` each time before  I run `kinvey status` I **do get the correct service version**.

```bash
➜  ms-graph-flex git:(develop) ✗ kinvey job
info:  Job status: ACTIVE - Pushing image (tag: 1.1.62).
➜  ms-graph-flex git:(develop) ✗ kinvey status
info:  Service status: ONLINE [v1.1.21]
➜  ms-graph-flex git:(develop) ✗ kinvey recycle
info:  Recycle initiated, received job e6f5f2ea704f4f738ef21179c138842f
➜  ms-graph-flex git:(develop) ✗ kinvey status
info:  Service status: ONLINE [v1.1.62]
➜  ms-graph-flex git:(develop) ✗ kinvey deploy # this deploy contained version 1.1.63
info:  Deploy initiated, received job 55a515156dae4d6691dbf1d54d0cce7c
➜  ms-graph-flex git:(develop) ✗ kinvey status
info:  Service status: ONLINE [v1.1.62]
```

When I did some more digging, the endpoint called in [service.js](https://github.com/Kinvey/kinvey-cli/blob/master/lib/service.js#L262) returns the previous application version if the [recycle endpoint](https://github.com/Kinvey/kinvey-cli/blob/master/lib/service.js#L241) is not first called. 

While this is not a blocker - maybe it is the intended behavior and I am misunderstanding the README - I figured it is something that you would want to be aware of!

**Comment by samlevin** [comment]
@kinson thanks for bringing this to our attention. A fix is already in progress and should be live either today or tomorrow. I'll reach out afterwardd to confirm that everything looks okay.

Best,
Sam

**Comment by samlevin** [comment]
@kinson next time you re-deploy the version should update as expected. thanks for bringing this to our attention!

Sam

**Comment by kinson** [comment]
@samlevin whoops I completely spaced on replying to this --  thanks for the update, everything is working great now 😎
